### ISSUE TITLE
How to set onClickListener on buttons within this View?

### ISSUE THREAD

**Issue by allenxuan** [iammert/MusicPlayerView#11]

**Comment by iammert** [comment]
Just like View.OnClickListener. 
```java
 mpv.setOnClickListener(new View.OnClickListener() {
      @Override public void onClick(View v) {
        if (mpv.isRotating()) {
          mpv.stop();
        } else {
          mpv.start();
        }
      }
    });
```

**Comment by allenxuan** [comment]
I wanna control all of the buttons , if possible. The previous-song button,
the next-song button , the play-pause button and the music progress bar.
What's are the IDs of these components?

**Comment by iammert** [comment]
Check project Readme how to control MusicPlayerView.
