### ISSUE TITLE
Error in compiling the library

### ISSUE THREAD

**Issue by bluemix** [iammert/MusicPlayerView#4]
Error:Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : uses-sdk:minSdkVersion 18 cannot be smaller than version 21 declared in library /home/bluemix/Cinemana/Cinemana-AppForSTB/app/build/intermediates/exploded-aar/com.github.iammert/MusicPlayerView/dc5f9ad3bc/AndroidManifest.xml
  	Suggestion: use tools:overrideLibrary="co.mobiwise.library" to force usage

**Comment by iammert** [comment]
I changed minimum sdk version from 21 to 14.

**Comment by iammert** [comment]
@bluemix I hope it s ok now.

**Comment by bluemix** [comment]
yes, now it works fine, although I had to use the library code instead from ```    compile 'com.github.iammert:MusicPlayerView:dc5f9ad3bc'```., also, I had to changed ```buttonColor``` in the styles, because I had conflicts with.

**Comment by swapps** [comment]
hi i'm having the same issue, how can i fix this

**Comment by iammert** [comment]
which jitpack version you are trying to build? @swapps

**Comment by swapps** [comment]
com.github.iammert:MusicPlayerView:dc5f9ad3bc
