### ISSUE TITLE
Make animation when click on Play/Pause button

### ISSUE THREAD

**Issue by anticafe** [iammert/MusicPlayerView#6]
I see there are 2 small libraries help us to animate Play/Pause button:
- https://github.com/alexjlockwood/material-pause-play-animation
- https://github.com/recruit-lifestyle/PlayPauseButton

Could you please integrate it into MusicPlayerView to make it more beautiful?

**Comment by iammert** [comment]
I really like them. I will integrate one of them. Thanks for suggestion

**Comment by anticafe** [comment]
You're welcome :)

**Comment by iammert** [comment]
What do you think now :) I just updated my library with material play/pause toggle. If you are ok, then issue may be closed :)

**Comment by anticafe** [comment]
@iammert Yeah, it looks great. Thanks for your work.
